[user]
algorithm = "cnn"

[graphics]
graphic_enabled = true
screen_width = 800
screen_height = 1000
fps = 120
title = "MineSweeper"
icon_path = "asset/images/icon.svg"

[game]
width = 10
height = 10
mines_percentage = 0.15

[cnn]
train_enabled = true
