[user]
algorithm = "rule_based"

[graphics]
graphic_enabled = true
screen_width = 1000
screen_height = 1000
fps = 240
title = "MineSweeper"
icon_path = "asset/images/icon.svg"
delay = 0
screen_capture = false

[game]
width = 20
height = 20
mines_percentage = 0.21

[cnn]
train_enabled = false
