[user]
algorithm = "cnn"

[graphics]
graphic_enabled = true
screen_width = 1000
screen_height = 1000
fps = 120
title = "MineSweeper"
icon_path = "asset/images/icon.svg"
delay = 1
screen_capture = false

[game]
width = 10
height = 10
mines_percentage = 0.1

[cnn]
train_enabled = true
